services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx-params.conf:/etc/nginx/conf.d/params.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=ian.gregory@mail.utoronto.ca
      - NGINX_PROXY_CONTAINER=nginx-proxy
  client:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/nybbler-client
    container_name: nybbler-client
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=nybbler.me
      - LETSENCRYPT_HOST=nybbler.me
  server:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/nybbler-server
    container_name: nybbler-server
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.nybbler.me
      - LETSENCRYPT_HOST=api.nybbler.me
      - CORS_ORIGIN=https://nybbler.me
      - POSTGRES_URL=postgres://nybbler:nybbler@nybbler-postgres:5432/nybbler
      - REDIS_HOST=nybbler-redis
      - REDIS_PORT=6379
    volumes:
      - uploads-volume:/usr/src/app/dist/uploads
  workers:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/nybbler-workers
    container_name: nybbler-workers
    restart: always
    environment:
      - POSTGRES_URL=postgres://nybbler:nybbler@nybbler-postgres:5432/nybbler
      - REDIS_HOST=nybbler-redis
      - REDIS_PORT=6379
    volumes:
      - uploads-volume:/usr/src/app/dist/uploads
  redis:
    image: redis:7.2.5-alpine
    container_name: nybbler-redis
    restart: always
    ports:
      - 6381:6379
  postgres:
    image: postgres:16
    container_name: nybbler-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=nybbler
      - POSTGRES_PASSWORD=nybbler
      - POSTGRES_DB=nybbler
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres16/:/docker-entrypoint-initdb.d/

volumes:
  uploads-volume:
  postgres-volume:
